import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Spec-Reki portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin></link>
        <link href="https://fonts.googleapis.com/css2?family=Comfortaa:wght@300;400;500;600;700&display=swap" rel="stylesheet"></link>
      </Head>

      <main className=' bg-white px-10 '>
        <section className=" h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className=' text-xl font-comfortaa'>Spec-Reki Enterprises</h1>
            <ul className='flex items-center'>
              <li><BsFillMoonStarsFill  className='cursor-pointer text-2xl'/></li>
              <li><a className=" bg-gradient-to-r from-red-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8" 
              href="#">Resume</a></li>
            </ul>
          </nav>
        </section>
      </main>

    </div>
  )
}
