import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Spec-Reki portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=' bg-white px-10 '>
        <section className=" h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className=' text-xl'>Spec-Reki Enterprises</h1>
            <ul className='flex items-center'>
              <li><BsFillMoonStarsFill/></li>
              <li><a href="#">Resume</a></li>
            </ul>
          </nav>
        </section>
      </main>

    </div>
  )
}
